version: "3"

services:
  db:
    image: "postgres:12"
    container_name: "oxy-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data